steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "northamerica-south1-docker.pkg.dev/orders-portal-447714/nestjs-course/image-registry/client-gateway",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "northamerica-south1-docker.pkg.dev/orders-portal-447714/nestjs-course/image-registry/client-gateway",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
